CREATE DATABASE IF NOT EXISTS tailor_shop
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE tailor_shop;

CREATE TABLE IF NOT EXISTS orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(20),
    email VARCHAR(150),
    neck DECIMAL(5, 2) NOT NULL,
    waist DECIMAL(5, 2) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'Pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
